import streamlit as st

st.set_page_config(
    page_title="InterQA",
    page_icon='💬',
    layout='wide'
)

st.header("Interactive Conversational Question Answering")
st.write("""
The application is an interactive Question Answering application based open source language models

- **Basic chatbot**: A chatbot that answers only based on the language model parametric Knowledge (zephyr-7b-beta)
- **Chat with Irish Documents**: A chatbot that answers questions about documents posted on gov.ie website between 27/06/2023 to 27/08/2023 (zephyr-7b-beta)
- **Chatbot with Internet Access**: An internet-enabled chatbot capable of answering user queries about recent events (llama-70b).
- **Chat with your documents** Empower the chatbot with the ability to access custom documents, enabling it to provide answers to user queries based on the referenced information (zephyr-7b-beta).
- **Tool Augumented with chat gpt** : An internet-enabled chatbot capable of answering user queries about recent events using chatgpt

**Disclamer**: The output generated by Large Language Model may be innacurate even with Augumented LLM
""")